apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ $.Release.Name }}-conf
    labels:
        app: {{ $.Release.Name }}
    namespace: {{ $.Release.Namespace }}
data:
    default.conf: |
        server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;
            
            location / {
                try_files   $uri $uri/ /index.html;
                root        /usr/share/nginx/html;
                index       index.html index.htm;
            }

            #error_page  404              /404.html;

            # redirect server error pages to the static page /50x.html
            #
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ $.Release.Name }}-html
    labels:
        app: {{ $.Release.Name }}
    namespace: {{ $.Release.Namespace }}
data:
    50x.html: |
        <!DOCTYPE html>
        <html>
        <head>
        <title>Error</title>
        <style>
            body {
                width: 35em;
                margin: 0 auto;
                font-family: Tahoma, Verdana, Arial, sans-serif;
            }
        </style>
        </head>
        <body>
        <h1>An error occurred.</h1>
        <p>Sorry, the page you are looking for is currently unavailable.<br/>
        Please try again later.</p>
        <p>If you are the system administrator of this resource then you should check
        the error log for details.</p>
        <p><em>Faithfully yours, nginx.</em></p>
        </body>
        </html>
    index.html: {{ .Values.html.index }}